// export { default as Button } from './Button/Button.jsx'
// export { default as Input } from './Input/Input.jsx'
export { default as Avatar } from './Avatar/Avatar'
export { default as Notice } from './Notice/Notice'
export { default as Search } from './Search/Search'
export { default as Book } from './Book/Book'
export { default as Friend } from './Friend/Friend'
export { default as FriendList } from './Friend/FriendList'
export { default as Rating } from './Rating/Rating'
